#!/bin/bash
# ----------------------------------------------------------------------------
# build-skills-corpus.sh — concatenate skills/<bundle>/*.md source files into
# upload-ready skills-corpus/<routing-skill>-corpus.md artifacts.
#
# Each corpus file uses `## file: <relative-path>` section anchors so the
# routing-Skill SKILL.md bodies can navigate by anchor rather than by token offset.
#
# Called by `make skills-corpus`. Outputs to skills-corpus/ (committed artifacts).
# See PLAN.md M13 P3 + spec §4.1.
#
# Copyright (C) 2026 R-fx Networks <proj@rfxn.com>
# Author: Ryan MacDonald <ryan@rfxn.com>
# License: GNU GPL v2
# ----------------------------------------------------------------------------

set -euo pipefail

SKILLS_DIR="${SKILLS_DIR:-skills}"
CORPUS_DIR="${CORPUS_DIR:-skills-corpus}"
MAX_BYTES=$((500 * 1024 * 1024))

command mkdir -p "$CORPUS_DIR"

# Bundle-to-corpus mapping (spec §4.1)
build_corpus() {
    local out="$CORPUS_DIR/$1"
    shift
    local sources=("$@")
    : > "$out.tmp"
    printf '# %s — generated corpus\n' "$(basename "$out" .md)" >> "$out.tmp"
    printf '\n_Generated by scripts/build-skills-corpus.sh from skills/<bundle>/*.md_\n\n' >> "$out.tmp"
    local src
    for src in "${sources[@]}"; do
        if [[ -d "$SKILLS_DIR/$src" ]]; then
            local f
            while IFS= read -r f; do
                [[ "$(basename "$f")" == "INDEX.md" ]] && continue
                printf '\n## file: %s\n\n' "${f#"$SKILLS_DIR/"}" >> "$out.tmp"
                command cat "$f" >> "$out.tmp"
            done < <(find "$SKILLS_DIR/$src" -maxdepth 1 -name '*.md' -type f | sort)
        elif [[ -f "$SKILLS_DIR/$src" ]]; then
            printf '\n## file: %s\n\n' "$src" >> "$out.tmp"
            command cat "$SKILLS_DIR/$src" >> "$out.tmp"
        else
            printf 'build-skills-corpus: WARNING: %s missing under %s/\n' "$src" "$SKILLS_DIR" >&2
        fi
    done
    local size_bytes
    size_bytes=$(command stat -c '%s' "$out.tmp" 2>/dev/null || command stat -f '%z' "$out.tmp") # -c is GNU/Linux; -f is BSD/macOS; suppress the error from whichever form is absent
    if (( size_bytes > MAX_BYTES )); then
        printf 'build-skills-corpus: ERROR: %s exceeds 500 MB cap (%d bytes)\n' "$out" "$size_bytes" >&2
        command rm -f "$out.tmp"
        exit 65
    fi
    command mv "$out.tmp" "$out"
    printf 'built %s (%s bytes)\n' "$out" "$size_bytes"
}

build_corpus foundations.md \
    "ir-playbook/case-lifecycle.md" \
    "ir-playbook/adversarial-content-handling.md"

build_corpus synthesizing-evidence-corpus.md \
    "ir-playbook/kill-chain-reconstruction.md" \
    "linux-forensics" \
    "timeline" \
    "ride-the-substrate" \
    "obfuscation"

build_corpus prescribing-defensive-payloads-corpus.md \
    "defense-synthesis" \
    "modsec-grammar" \
    "apf-grammar" \
    "remediation"

build_corpus curating-cases-corpus.md \
    "ir-playbook/case-lifecycle.md" \
    "agentic-minutes-playbook"

build_corpus gating-false-positives-corpus.md \
    "false-positives"

build_corpus extracting-iocs-corpus.md \
    "ioc-aggregation" \
    "actor-attribution" \
    "webshell-families"

build_corpus authoring-incident-briefs-corpus.md \
    "ic-brief-format"

build_corpus substrate-context-corpus.md \
    "apsb25-94" \
    "magento-attacks" \
    "legacy-os-pitfalls" \
    "hosting-stack" \
    "shared-hosting-attack-shapes"
