# blacklight RPM spec — generated by pkg_gen.sh from pkg_lib templates
# Customized for single-binary layout: /usr/bin/bl + /var/lib/bl state dirs
#
%define name    blacklight
%define version 0.1.0
%define release 1%{?dist}

Name:           %{name}
Version:        %{version}
Release:        %{release}
Summary:        blacklight — agent-directed defensive forensics for Linux
License:        GPLv2+
URL:            https://github.com/rfxn/blacklight
Source0:        %{name}-%{version}.tar.gz
BuildArch:      noarch

Requires:       bash >= 4.1
Requires:       coreutils
Requires:       curl
Requires:       jq

%description
blacklight is a single-file bash wrapper directed by a skills-native Managed Agent. It supercharges fifteen years of Linux OSS defensive primitives (iptables, mod_security, ClamAV, LMD, APF, YARA, Apache logs, .htaccess walks, crontab audits) with an always-on curator that persists case state across sim-days. No platform buy-in. No fleet migration.

%prep
%setup -q -n %{name}-%{version}

%build
# Nothing to build — bl is a bash script

%install
rm -rf %{buildroot}
install -D -m 755 bl %{buildroot}/usr/bin/bl
install -D -m 644 README.md %{buildroot}/usr/share/doc/blacklight/README.md
install -D -m 644 CHANGELOG %{buildroot}/usr/share/doc/blacklight/CHANGELOG
install -d -m 750 %{buildroot}/var/lib/bl
install -d -m 750 %{buildroot}/var/lib/bl/state
install -d -m 750 %{buildroot}/var/lib/bl/ledger
install -d -m 750 %{buildroot}/var/lib/bl/outbox

%pre
# Nothing required

%post
# Nothing required — bl self-provisions /var/lib/bl on first run.
:

%preun
# Nothing required

%postun
if [ "$1" = "0" ]; then
    # Full removal — clean runtime state (ledger, outbox, state)
    command rm -rf /var/lib/bl 2>/dev/null || true   # state dir may already be absent
fi

%files
%license LICENSE
%attr(755,root,root) /usr/bin/bl
%dir %attr(750,root,root) /var/lib/bl
%dir %attr(750,root,root) /var/lib/bl/state
%dir %attr(750,root,root) /var/lib/bl/ledger
%dir %attr(750,root,root) /var/lib/bl/outbox
%doc /usr/share/doc/blacklight/README.md
%doc /usr/share/doc/blacklight/CHANGELOG

%changelog
* Fri Apr 24 2026 R-fx Networks <proj@rfxn.com> - 0.1.0-1
- Initial package release
