# blacklight RPM spec — generated by pkg_gen.sh from pkg_lib templates
# Customized for single-binary layout: /usr/bin/bl + /var/lib/bl state dirs
#
%define name    blacklight
%define version 0.7.0
%define release 1%{?dist}

Name:           %{name}
Version:        %{version}
Release:        %{release}
Summary:        blacklight — agent-directed defensive forensics for Linux
License:        GPLv2+
URL:            https://github.com/rfxn/blacklight
Source0:        %{name}-%{version}.tar.gz
BuildArch:      noarch

Requires:       bash >= 4.1
Requires:       coreutils
Requires:       curl
Requires:       jq

%description
blacklight is a single-file bash wrapper directed by a skills-native Managed Agent. It supercharges fifteen years of Linux OSS defensive primitives (iptables, mod_security, ClamAV, LMD, APF, YARA, Apache logs, .htaccess walks, crontab audits) with an always-on curator that persists case state across sim-days. No platform buy-in. No fleet migration.

%prep
%setup -q -n %{name}-%{version}

%build
# Nothing to build — bl is a bash script

%install
rm -rf %{buildroot}
install -D -m 755 bl %{buildroot}/usr/bin/bl
install -D -m 644 README.md %{buildroot}/usr/share/doc/blacklight/README.md
install -D -m 644 CHANGELOG %{buildroot}/usr/share/doc/blacklight/CHANGELOG
install -d -m 750 %{buildroot}/var/lib/bl
install -d -m 750 %{buildroot}/var/lib/bl/state
install -d -m 750 %{buildroot}/var/lib/bl/ledger
install -d -m 750 %{buildroot}/var/lib/bl/outbox

%pre
# Nothing required

%post
# Nothing required — bl self-provisions /var/lib/bl on first run.
:

%preun
# Nothing required

%postun
if [ "$1" = "0" ]; then
    # Full removal — clean runtime state (ledger, outbox, state)
    command rm -rf /var/lib/bl 2>/dev/null || true   # state dir may already be absent
fi

%files
%license LICENSE
%attr(755,root,root) /usr/bin/bl
%dir %attr(750,root,root) /var/lib/bl
%dir %attr(750,root,root) /var/lib/bl/state
%dir %attr(750,root,root) /var/lib/bl/ledger
%dir %attr(750,root,root) /var/lib/bl/outbox
%doc /usr/share/doc/blacklight/README.md
%doc /usr/share/doc/blacklight/CHANGELOG

%changelog
* Tue Apr 28 2026 R-fx Networks <proj@rfxn.com> - 0.7.0-1
- M17 Managed Agents primitive correction:
  Two primitives that were diagnosed at thinner-than-canonical depth in M13/M14
  re-probed and corrected against the live API.
  Environments now bake the curator's nine-deb package set via config.packages.apt
  (apache2, libapache2-mod-security2, modsecurity-crs, yara, jq, zstd, duckdb,
  pandoc, weasyprint); cold sessions stop re-installing per-case via the bash tool.
  Routing skills are now first-class workspace Skills (six custom + pdf Anthropic
  pre-built), seeded via bl_setup_seed_skills_native (multipart upload, sha256
  bundle idempotency, version-bump branch on content change). bl_setup_seed_skills
  routes to _native unconditionally; the Files-API workspace-files fallback path
  (Path C / bl_setup_seed_skills_as_files) deleted. Curator agent body emits
  skills:[] with version: "latest" auto-pickup; resources:[] reference of old
  workspace skill files removed. prompts/curator-agent.md path-routing prose
  stripped (-30 lines); description-router selection is platform-routed. Each
  routing-skills/<name>/ now bundles a per-skill foundations.md Level-3 reference;
  six SKILL.md files carry YAML frontmatter (name + description ≤1024 chars).
  ANTHROPIC-API-NOTES.md §1 (Environments) and §2 (Skills allowlist) marked
  RESOLVED 2026-04-28 — the §2 404 was a self-inflicted wrong-beta-header bug;
  canonical trio skills-2025-10-02,code-execution-2025-08-25,files-api-2025-04-14
  documented; new §11 captures research-preview-only Messages-API features
  (cache_control, thinking) that Managed Agents does not surface. Beta-header
  strings centralized in src/bl.d/20-api.sh as BL_API_BETA_{MA,FILES,SKILLS}
  constants. bl_setup_skills_gc archives 3 v1 orphan skills (case-lifecycle,
  polyshell, modsec-patterns) and deletes old workspace skill files via
  bl setup --gc. tests/16-skills-native.bats new (8 tests); tests/Dockerfile +
  tests/Dockerfile.rocky9 install zip + sanity check. 424/424 pre-commit matrix
  on debian12 + rocky9.

* Sun Apr 26 2026 R-fx Networks <proj@rfxn.com> - 0.6.0-1
- M16 collectors + bridge milestone: modsec parser fix + canonical 8-hex
  corpus alignment; bl observe cron --from-file fixture-mode adapter;
  session-event → memstore-pending bridge (closes M12.5 gap); writeback
  emits user.custom_tool_result for bridge-enriched steps; args translator
  + per-verb observe adapters (11 verbs). Curator end-to-end loop runs
  cleanly; full debian12 suite 398/398 across milestone.

* Sun Apr 26 2026 R-fx Networks <proj@rfxn.com> - 0.5.2-1
- Operator config tree expansion (/etc/blacklight/blacklight.conf):
  preflight loader allowlist grows from 7 → 22 keys. New conf-tunable
  surfaces: log_level, disable_llm, notify_dir, cpanel_dir, defend
  tunables (extra_cdn_asns, fw_allow_broad_ip, fp_corpus, asn_cache),
  clean tunables (dryrun_ttl_secs, proc_grace_secs), obs_journal_max,
  scanner sig dirs (lmd_sig_dir, clamav_sig_dir, yara_rules_dir),
  repo_url. Every new key maps 1:1 to a real ${BL_<KEY>:-default}
  consumer in src/bl.d/; documented defaults match source defaults
  exactly. files/etc/blacklight.conf.default populated with grouped
  sections + an env-only knob footer (BL_VAR_DIR / BL_BLACKLIGHT_DIR /
  BL_HOST_LABEL / BL_INVOKED_BY / BL_UNATTENDED*) that cannot live in
  the conf due to bootstrap order. bl_setup_local_preflight now also
  invokes _bl_load_blacklight_conf so conf-driven knobs (log_level,
  repo_url) take effect for `bl setup`, which bypasses bl_preflight by
  design. Outbox tunables remain readonly constants — comment in conf
  updated to state this explicitly rather than implicitly.

* Sun Apr 26 2026 R-fx Networks <proj@rfxn.com> - 0.5.1-1
- Documentation + exhibit consolidation pass on top of 0.5.0:
  DESIGN.md gains §3.4 skill-version pinning at session-create, §8.8
  workspace recovery from lost state.json, §12.7 deliberately-not-used
  primitives (callable_agents, mcp_servers). README + PRD reframed —
  Try-it walkthrough, three architecture views, Bash SDK section, broken
  docs/demo/ links replaced with tests/live/ pointers (docs/demo/ is
  operator-local). FUTURE.md re-organized into eight strategic themes
  with phased delivery and item-level technical briefs. Six routing
  Skills receive an adversarial-content-handling anti-pattern (#6) and
  description.txt voice/tone refresh. Exhibits hosts 4/5/7 gain
  modsec_audit.log + journal.json so the cross-stream correlation chain
  resolves on every staged host; host-3 carries an empty-by-design
  marker. docs/managed-agents.md gains a §6 framing of the deliberately
  non-used primitives.

* Sun Apr 26 2026 R-fx Networks <proj@rfxn.com> - 0.5.0-1
- M15 + post-M15 consolidation: live API correctness against the
  managed-agents-2026-04-01 beta surface and integration-notes formalization.
  Sessions events shape migrated to the new {events:[...]} wrapper across
  27-outbox.sh / 50-consult.sh / 60-run.sh / 70-case.sh after silent breaking
  change in upstream beta (bare-event was working through M12 P5.5; new
  wrapper required as of M15 P8 live smoke). Sessions.create body now carries
  agent (not agent_id) + environment_id + resources[] (P5/F12). Environments
  body migrated to canonical config.type/config.networking.unrestricted shape
  after probing rejection of legacy packages/networking top-level fields;
  apt-package install is now session-driven via the curator bash tool until
  the API exposes a setup-script field. Skills API workspace allowlist fall-
  back: bl_setup_seed_skills_as_files uploads each routing-skill SKILL.md as
  a corpus File at /skills/<name>-skill.md when /v1/skills returns 404. Skills
  API probe rewritten with body+status parsing portable across real curl AND
  the curator-mock test shim. bl_preflight seeds BL_MEMSTORE_CASE_ID from
  state.json before the cached-agent-id early-return path (closes M15 fallout
  where post-migration consult/run verbs collapsed to literal default).
  Live integration smoke (tests/live/setup-live.bats) runs end-to-end against
  the real Anthropic workspace under BL_LIVE=1 (4/4 green): setup --sync,
  setup --check, consult --new with corpora attached, setup --reset --force
  archive verb. Hermetic suite restored to 348/0 on debian12 + rocky9 after
  P6 agent-body-shape test rewritten to assert the managed-agents-2026-04-01
  contract (name + model + system + tools[]; forbidden: skill_versions,
  thinking, output_config). New top-level docs: ANTHROPIC-API-NOTES.md
  (operator log of 10 numbered API friction points with severity tags +
  workarounds), HACKATHON_TIMELINE.md (6-day development record:
  v1 hackathon scaffolding through pivot to v2 milestone-driven rebuild
  through M15 close). DESIGN.md / PRD.md / FUTURE.md re-promoted to
  committed top-level docs (operator-tracked, no longer working files).
  Archive housekeeping: .rdf/archive/Mx/ → .rdf/archive/2026-04-XX-Mx/
  with date-prefixed milestone dirs; M13 plan moved from loose archive root
  into 2026-04-25-M13/PLAN-M13.md; final DESIGN.md snapshot relocated into
  2026-04-26-M15-final/.
* Sun Apr 26 2026 R-fx Networks <proj@rfxn.com> - 0.4.0-1
- M14 substrate-hook (closed-loop response layer for LMD + ModSec on cPanel EA4):
  vendored alert_lib v1.0.6 + tlog_lib v2.0.5 (slot 05/06 generated parts);
  bl_notify multi-channel wrapper with notify_dispatched / notify_failed ledger
  emission and notify.d/* channel registration; bl_consult_new dual-mode argv
  (positional preserved; new --fingerprint + --dedup-window-hours flag-form);
  bl trigger lmd verb + files/hooks/bl-lmd-hook adapter for LMD post_scan_hook
  integration (lmd_hook_received + lmd_hit_degraded ledger events); cPanel Stage 4
  ModSec userdata lock-in (45-cpanel.sh) with two-stage rollback +
  cpanel_lockin_invoked / cpanel_lockin_failed / cpanel_lockin_rolled_back events;
  G5 unattended-mode tier policy gate in 60-run.sh + bl_run_queue_unattended;
  bl setup --install-hook lmd / --import-from-lmd verbs; /etc/blacklight/ +
  notify.d/ + hooks/ provisioning in install.sh (cp -n preserves operator conf
  on upgrade) + post_scan_hook removal + conf-tree prompt in uninstall.sh;
  three new description-routed skill bundles (bl-capabilities, lmd-triggers,
  cpanel-easyapache); docs/action-tiers.md §5.6 unattended-mode gate overrides.
* Sat Apr 25 2026 R-fx Networks <proj@rfxn.com> - 0.3.0-1
- M13 Skills primitive realignment (Path C): six routing Skills + 8 workspace corpora
  via Anthropic Skills + Files APIs; bl-skills memstore retired, bl-case retained for
  per-case curator working memory; per-case raw evidence migrated to per-source rolling
  Files uploads driven by threshold/rotate helpers; state migrated to single state.json
  with first-run per-key-file migration; bl setup verb dispatcher rewritten with
  --sync/--reset/--gc/--eval/--check; live promotion eval gate (50 cases, BL_EVAL_LIVE=1);
  curator system prompt §3 rewritten for Path C primitives + new §9 anti-pattern;
  skills/INDEX.md router retired (routing now via Skill descriptions + harness).
* Sat Apr 25 2026 R-fx Networks <proj@rfxn.com> - 0.2.0-1
- M11 posture lift: real three-tier model routing (Opus 4.7 / Sonnet 4.6 / Haiku 4.5),
  bl_poll_pending GET-poll loop, synthesize_defense + reconstruct_intent custom-tool
  consumption hooks, README walkthrough end-to-end correction, exhibits/fleet-01
  beef-up to ~100K tokens, 5 negative tests + 8 model-routing tests, security-model
  documentation, install-validation evidence; 250/250 BATS green debian12 + rocky9.
* Fri Apr 24 2026 R-fx Networks <proj@rfxn.com> - 0.1.0-1
- Initial package release
